[homebrew]
cleanup = "uninstall"
brews = ["mas", "mole"]
casks = [
  "android-platform-tools",
  "apparency",
  "audacity",
  "azookey",
  "firefox@developer-edition",
  "ghostty@tip",
  "iina",
  "inkscape",
  "karabiner-elements",
  "keyboardcleantool",
  "openmtp",
  "orbstack",
  "stats",
  "tailscale-app",
  "upscayl",
  "vesktop",
  "visual-studio-code",
  "vivaldi",
  "xcodes-app",
  "li-na/zed-i18n/zed-i18n",
  "zen",
  "abue-ammar/tinycast/tinycast",
]
taps = ["abue-ammar/tinycast", "artginzburg/tap", "li-na/zed-i18n"]

[homebrew.masApps]
Amphetamine = 937984704
Bitwarden = 1352778147
"Draw Things" = 6444050820
RunCatNeo = 6757801838
Shelv = 6762255865
