[nix]
packages = [
  "bat",
  "chezmoi",
  "eza",
  "fastfetch",
  "ffmpeg",
  "fzf",
  "gh",
  "git",
  "gnupg",
  "mise",
  "nano",
  "ripgrep",
  "sheldon",
  "tokei",
  "zoxide",
]
fonts = ["ibm-plex.sans-jp", "monaspace", "nerd-fonts.monaspace"]
