[tools]
bun = "latest"
deno = "latest"
node = "lts"
"npm:@antfu/ni" = "latest"
"npm:npm" = "latest"
"npm:npm-check-updates" = "latest"
"npm:pnpm" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
