name: Dotfiles CI
on:
  push:
    paths:
      - "home/**"

permissions:
  contents: read

jobs:
  apply_test_macos:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apply_test_macos
      cancel-in-progress: true
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run chezmoi apply
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --branch "$GITHUB_REF_NAME" -v ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}

  apply_test_linux:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apply_test_linux
      cancel-in-progress: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run chezmoi apply
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --branch "$GITHUB_REF_NAME" -v ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
