name: Dotfiles CI
on:
  push:
    paths:
      - 'home/**'

jobs:
  apply_test_macos:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apply_test_macos
      cancel-in-progress: true
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run chezmoi apply
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply -v ${{ github.repository_owner }}
  apply_test_linux:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apply_test_linux
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install zsh
        run: |
            sudo apt update -y
            sudo apt install -y zsh

      - name: Run chezmoi apply
        shell: zsh {0}
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply -v ${{ github.repository_owner }}
